// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: api/agentd/v1/agentd.proto

package agentdv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command_Kind int32

const (
	Command_UNSPECIFIED        Command_Kind = 0
	Command_START              Command_Kind = 1
	Command_STOP               Command_Kind = 2
	Command_RESTART            Command_Kind = 3
	Command_INTERRUPT          Command_Kind = 4
	Command_STATUS             Command_Kind = 5
	Command_PREPARE_CHECKPOINT Command_Kind = 6
	Command_EXECUTE            Command_Kind = 7
	Command_SIGNAL             Command_Kind = 8
)

// Enum value maps for Command_Kind.
var (
	Command_Kind_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "START",
		2: "STOP",
		3: "RESTART",
		4: "INTERRUPT",
		5: "STATUS",
		6: "PREPARE_CHECKPOINT",
		7: "EXECUTE",
		8: "SIGNAL",
	}
	Command_Kind_value = map[string]int32{
		"UNSPECIFIED":        0,
		"START":              1,
		"STOP":               2,
		"RESTART":            3,
		"INTERRUPT":          4,
		"STATUS":             5,
		"PREPARE_CHECKPOINT": 6,
		"EXECUTE":            7,
		"SIGNAL":             8,
	}
)

func (x Command_Kind) Enum() *Command_Kind {
	p := new(Command_Kind)
	*p = x
	return p
}

func (x Command_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_api_agentd_v1_agentd_proto_enumTypes[0].Descriptor()
}

func (Command_Kind) Type() protoreflect.EnumType {
	return &file_api_agentd_v1_agentd_proto_enumTypes[0]
}

func (x Command_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command_Kind.Descriptor instead.
func (Command_Kind) EnumDescriptor() ([]byte, []int) {
	return file_api_agentd_v1_agentd_proto_rawDescGZIP(), []int{6, 0}
}

type Observation_Kind int32

const (
	Observation_UNSPECIFIED         Observation_Kind = 0
	Observation_PROCESS_STATUS      Observation_Kind = 1
	Observation_CANDIDATE_EVENT     Observation_Kind = 2
	Observation_CHECKPOINT_PREPARED Observation_Kind = 3
	Observation_DIAGNOSTIC          Observation_Kind = 4
)

// Enum value maps for Observation_Kind.
var (
	Observation_Kind_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "PROCESS_STATUS",
		2: "CANDIDATE_EVENT",
		3: "CHECKPOINT_PREPARED",
		4: "DIAGNOSTIC",
	}
	Observation_Kind_value = map[string]int32{
		"UNSPECIFIED":         0,
		"PROCESS_STATUS":      1,
		"CANDIDATE_EVENT":     2,
		"CHECKPOINT_PREPARED": 3,
		"DIAGNOSTIC":          4,
	}
)

func (x Observation_Kind) Enum() *Observation_Kind {
	p := new(Observation_Kind)
	*p = x
	return p
}

func (x Observation_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Observation_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_api_agentd_v1_agentd_proto_enumTypes[1].Descriptor()
}

func (Observation_Kind) Type() protoreflect.EnumType {
	return &file_api_agentd_v1_agentd_proto_enumTypes[1]
}

func (x Observation_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Observation_Kind.Descriptor instead.
func (Observation_Kind) EnumDescriptor() ([]byte, []int) {
	return file_api_agentd_v1_agentd_proto_rawDescGZIP(), []int{7, 0}
}

type Heartbeat_ProcessState int32

const (
	Heartbeat_UNSPECIFIED Heartbeat_ProcessState = 0
	Heartbeat_ABSENT      Heartbeat_ProcessState = 1
	Heartbeat_STARTING    Heartbeat_ProcessState = 2
	Heartbeat_RUNNING     Heartbeat_ProcessState = 3
	Heartbeat_STOPPING    Heartbeat_ProcessState = 4
	Heartbeat_EXITED      Heartbeat_ProcessState = 5
	Heartbeat_FAILED      Heartbeat_ProcessState = 6
)

// Enum value maps for Heartbeat_ProcessState.
var (
	Heartbeat_ProcessState_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "ABSENT",
		2: "STARTING",
		3: "RUNNING",
		4: "STOPPING",
		5: "EXITED",
		6: "FAILED",
	}
	Heartbeat_ProcessState_value = map[string]int32{
		"UNSPECIFIED": 0,
		"ABSENT":      1,
		"STARTING":    2,
		"RUNNING":     3,
		"STOPPING":    4,
		"EXITED":      5,
		"FAILED":      6,
	}
)

func (x Heartbeat_ProcessState) Enum() *Heartbeat_ProcessState {
	p := new(Heartbeat_ProcessState)
	*p = x
	return p
}

func (x Heartbeat_ProcessState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Heartbeat_ProcessState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_agentd_v1_agentd_proto_enumTypes[2].Descriptor()
}

func (Heartbeat_ProcessState) Type() protoreflect.EnumType {
	return &file_api_agentd_v1_agentd_proto_enumTypes[2]
}

func (x Heartbeat_ProcessState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Heartbeat_ProcessState.Descriptor instead.
func (Heartbeat_ProcessState) EnumDescriptor() ([]byte, []int) {
	return file_api_agentd_v1_agentd_proto_rawDescGZIP(), []int{9, 0}
}

type Rotation_Kind int32

const (
	Rotation_UNSPECIFIED Rotation_Kind = 0
	Rotation_REQUEST     Rotation_Kind = 1
	Rotation_ISSUED      Rotation_Kind = 2
)

// Enum value maps for Rotation_Kind.
var (
	Rotation_Kind_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "REQUEST",
		2: "ISSUED",
	}
	Rotation_Kind_value = map[string]int32{
		"UNSPECIFIED": 0,
		"REQUEST":     1,
		"ISSUED":      2,
	}
)

func (x Rotation_Kind) Enum() *Rotation_Kind {
	p := new(Rotation_Kind)
	*p = x
	return p
}

func (x Rotation_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Rotation_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_api_agentd_v1_agentd_proto_enumTypes[3].Descriptor()
}

func (Rotation_Kind) Type() protoreflect.EnumType {
	return &file_api_agentd_v1_agentd_proto_enumTypes[3]
}

func (x Rotation_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Rotation_Kind.Descriptor instead.
func (Rotation_Kind) EnumDescriptor() ([]byte, []int) {
	return file_api_agentd_v1_agentd_proto_rawDescGZIP(), []int{10, 0}
}

type Failure_Code int32

const (
	Failure_UNSPECIFIED     Failure_Code = 0
	Failure_INCOMPATIBLE    Failure_Code = 1
	Failure_STALE           Failure_Code = 2
	Failure_MALFORMED       Failure_Code = 3
	Failure_LIMIT_EXCEEDED  Failure_Code = 4
	Failure_UNAVAILABLE     Failure_Code = 5
	Failure_OUTCOME_UNKNOWN Failure_Code = 6
)

// Enum value maps for Failure_Code.
var (
	Failure_Code_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "INCOMPATIBLE",
		2: "STALE",
		3: "MALFORMED",
		4: "LIMIT_EXCEEDED",
		5: "UNAVAILABLE",
		6: "OUTCOME_UNKNOWN",
	}
	Failure_Code_value = map[string]int32{
		"UNSPECIFIED":     0,
		"INCOMPATIBLE":    1,
		"STALE":           2,
		"MALFORMED":       3,
		"LIMIT_EXCEEDED":  4,
		"UNAVAILABLE":     5,
		"OUTCOME_UNKNOWN": 6,
	}
)

func (x Failure_Code) Enum() *Failure_Code {
	p := new(Failure_Code)
	*p = x
	return p
}

func (x Failure_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Failure_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_api_agentd_v1_agentd_proto_enumTypes[4].Descriptor()
}

func (Failure_Code) Type() protoreflect.EnumType {
	return &file_api_agentd_v1_agentd_proto_enumTypes[4]
}

func (x Failure_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Failure_Code.Descriptor instead.
func (Failure_Code) EnumDescriptor() ([]byte, []int) {
	return file_api_agentd_v1_agentd_proto_rawDescGZIP(), []int{11, 0}
}

type VersionRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Major         uint32                 `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	MinimumMinor  uint32                 `protobuf:"varint,2,opt,name=minimum_minor,json=minimumMinor,proto3" json:"minimum_minor,omitempty"`
	MaximumMinor  uint32                 `protobuf:"varint,3,opt,name=maximum_minor,json=maximumMinor,proto3" json:"maximum_minor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionRange) Reset() {
	*x = VersionRange{}
	mi := &file_api_agentd_v1_agentd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionRange) ProtoMessage() {}

func (x *VersionRange) ProtoReflect() protoreflect.Message {
	mi := &file_api_agentd_v1_agentd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionRange.ProtoReflect.Descriptor instead.
func (*VersionRange) Descriptor() ([]byte, []int) {
	return file_api_agentd_v1_agentd_proto_rawDescGZIP(), []int{0}
}

func (x *VersionRange) GetMajor() uint32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *VersionRange) GetMinimumMinor() uint32 {
	if x != nil {
		return x.MinimumMinor
	}
	return 0
}

func (x *VersionRange) GetMaximumMinor() uint32 {
	if x != nil {
		return x.MaximumMinor
	}
	return 0
}

type Binding struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TenantId          string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SessionId         string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ExecutionId       string                 `protobuf:"bytes,3,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	AttemptId         string                 `protobuf:"bytes,4,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	SandboxBindingId  string                 `protobuf:"bytes,5,opt,name=sandbox_binding_id,json=sandboxBindingId,proto3" json:"sandbox_binding_id,omitempty"`
	SessionGeneration uint64                 `protobuf:"varint,6,opt,name=session_generation,json=sessionGeneration,proto3" json:"session_generation,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Binding) Reset() {
	*x = Binding{}
	mi := &file_api_agentd_v1_agentd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Binding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Binding) ProtoMessage() {}

func (x *Binding) ProtoReflect() protoreflect.Message {
	mi := &file_api_agentd_v1_agentd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Binding.ProtoReflect.Descriptor instead.
func (*Binding) Descriptor() ([]byte, []int) {
	return file_api_agentd_v1_agentd_proto_rawDescGZIP(), []int{1}
}

func (x *Binding) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Binding) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Binding) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *Binding) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *Binding) GetSandboxBindingId() string {
	if x != nil {
		return x.SandboxBindingId
	}
	return ""
}

func (x *Binding) GetSessionGeneration() uint64 {
	if x != nil {
		return x.SessionGeneration
	}
	return 0
}

type Limits struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	FrameBytes          uint32                 `protobuf:"varint,1,opt,name=frame_bytes,json=frameBytes,proto3" json:"frame_bytes,omitempty"`
	CommandBytes        uint32                 `protobuf:"varint,2,opt,name=command_bytes,json=commandBytes,proto3" json:"command_bytes,omitempty"`
	EventBytes          uint32                 `protobuf:"varint,3,opt,name=event_bytes,json=eventBytes,proto3" json:"event_bytes,omitempty"`
	DiagnosticBytes     uint32                 `protobuf:"varint,4,opt,name=diagnostic_bytes,json=diagnosticBytes,proto3" json:"diagnostic_bytes,omitempty"`
	MutatingInflight    uint32                 `protobuf:"varint,5,opt,name=mutating_inflight,json=mutatingInflight,proto3" json:"mutating_inflight,omitempty"`
	ReadonlyInflight    uint32                 `protobuf:"varint,6,opt,name=readonly_inflight,json=readonlyInflight,proto3" json:"readonly_inflight,omitempty"`
	BufferedEvents      uint32                 `protobuf:"varint,7,opt,name=buffered_events,json=bufferedEvents,proto3" json:"buffered_events,omitempty"`
	BufferedBytes       uint32                 `protobuf:"varint,8,opt,name=buffered_bytes,json=bufferedBytes,proto3" json:"buffered_bytes,omitempty"`
	HeartbeatIntervalMs uint32                 `protobuf:"varint,9,opt,name=heartbeat_interval_ms,json=heartbeatIntervalMs,proto3" json:"heartbeat_interval_ms,omitempty"`
	LivenessWindowMs    uint32                 `protobuf:"varint,10,opt,name=liveness_window_ms,json=livenessWindowMs,proto3" json:"liveness_window_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Limits) Reset() {
	*x = Limits{}
	mi := &file_api_agentd_v1_agentd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Limits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Limits) ProtoMessage() {}

func (x *Limits) ProtoReflect() protoreflect.Message {
	mi := &file_api_agentd_v1_agentd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Limits.ProtoReflect.Descriptor instead.
func (*Limits) Descriptor() ([]byte, []int) {
	return file_api_agentd_v1_agentd_proto_rawDescGZIP(), []int{2}
}

func (x *Limits) GetFrameBytes() uint32 {
	if x != nil {
		return x.FrameBytes
	}
	return 0
}

func (x *Limits) GetCommandBytes() uint32 {
	if x != nil {
		return x.CommandBytes
	}
	return 0
}

func (x *Limits) GetEventBytes() uint32 {
	if x != nil {
		return x.EventBytes
	}
	return 0
}

func (x *Limits) GetDiagnosticBytes() uint32 {
	if x != nil {
		return x.DiagnosticBytes
	}
	return 0
}

func (x *Limits) GetMutatingInflight() uint32 {
	if x != nil {
		return x.MutatingInflight
	}
	return 0
}

func (x *Limits) GetReadonlyInflight() uint32 {
	if x != nil {
		return x.ReadonlyInflight
	}
	return 0
}

func (x *Limits) GetBufferedEvents() uint32 {
	if x != nil {
		return x.BufferedEvents
	}
	return 0
}

func (x *Limits) GetBufferedBytes() uint32 {
	if x != nil {
		return x.BufferedBytes
	}
	return 0
}

func (x *Limits) GetHeartbeatIntervalMs() uint32 {
	if x != nil {
		return x.HeartbeatIntervalMs
	}
	return 0
}

func (x *Limits) GetLivenessWindowMs() uint32 {
	if x != nil {
		return x.LivenessWindowMs
	}
	return 0
}

type Hello struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Versions              *VersionRange          `protobuf:"bytes,1,opt,name=versions,proto3" json:"versions,omitempty"`
	Binding               *Binding               `protobuf:"bytes,2,opt,name=binding,proto3" json:"binding,omitempty"`
	Challenge             []byte                 `protobuf:"bytes,3,opt,name=challenge,proto3" json:"challenge,omitempty"` // 32 bytes supplied by trusted bootstrap/connection setup.
	BuildDigest           string                 `protobuf:"bytes,4,opt,name=build_digest,json=buildDigest,proto3" json:"build_digest,omitempty"`
	AdapterKind           string                 `protobuf:"bytes,5,opt,name=adapter_kind,json=adapterKind,proto3" json:"adapter_kind,omitempty"`
	AdapterDigest         string                 `protobuf:"bytes,6,opt,name=adapter_digest,json=adapterDigest,proto3" json:"adapter_digest,omitempty"`
	SupportedCapabilities []string               `protobuf:"bytes,7,rep,name=supported_capabilities,json=supportedCapabilities,proto3" json:"supported_capabilities,omitempty"`
	RequiredCapabilities  []string               `protobuf:"bytes,8,rep,name=required_capabilities,json=requiredCapabilities,proto3" json:"required_capabilities,omitempty"`
	Limits                *Limits                `protobuf:"bytes,9,opt,name=limits,proto3" json:"limits,omitempty"`
	BootstrapProof        []byte                 `protobuf:"bytes,10,opt,name=bootstrap_proof,json=bootstrapProof,proto3" json:"bootstrap_proof,omitempty"` // Transport verifies/consumes; never part of evidence.
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_api_agentd_v1_agentd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_api_agentd_v1_agentd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_api_agentd_v1_agentd_proto_rawDescGZIP(), []int{3}
}

func (x *Hello) GetVersions() *VersionRange {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *Hello) GetBinding() *Binding {
	if x != nil {
		return x.Binding
	}
	return nil
}

func (x *Hello) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *Hello) GetBuildDigest() string {
	if x != nil {
		return x.BuildDigest
	}
	return ""
}

func (x *Hello) GetAdapterKind() string {
	if x != nil {
		return x.AdapterKind
	}
	return ""
}

func (x *Hello) GetAdapterDigest() string {
	if x != nil {
		return x.AdapterDigest
	}
	return ""
}

func (x *Hello) GetSupportedCapabilities() []string {
	if x != nil {
		return x.SupportedCapabilities
	}
	return nil
}

func (x *Hello) GetRequiredCapabilities() []string {
	if x != nil {
		return x.RequiredCapabilities
	}
	return nil
}

func (x *Hello) GetLimits() *Limits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *Hello) GetBootstrapProof() []byte {
	if x != nil {
		return x.BootstrapProof
	}
	return nil
}

type Welcome struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Major             uint32                 `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	Minor             uint32                 `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	Binding           *Binding               `protobuf:"bytes,3,opt,name=binding,proto3" json:"binding,omitempty"`
	Challenge         []byte                 `protobuf:"bytes,4,opt,name=challenge,proto3" json:"challenge,omitempty"`
	ConnectionId      string                 `protobuf:"bytes,5,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	ConnectionEpoch   uint64                 `protobuf:"varint,6,opt,name=connection_epoch,json=connectionEpoch,proto3" json:"connection_epoch,omitempty"`
	Capabilities      []string               `protobuf:"bytes,7,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Limits            *Limits                `protobuf:"bytes,8,opt,name=limits,proto3" json:"limits,omitempty"`
	NegotiationDigest string                 `protobuf:"bytes,9,opt,name=negotiation_digest,json=negotiationDigest,proto3" json:"negotiation_digest,omitempty"`
	BuildDigest       string                 `protobuf:"bytes,10,opt,name=build_digest,json=buildDigest,proto3" json:"build_digest,omitempty"`
	AdapterKind       string                 `protobuf:"bytes,11,opt,name=adapter_kind,json=adapterKind,proto3" json:"adapter_kind,omitempty"`
	AdapterDigest     string                 `protobuf:"bytes,12,opt,name=adapter_digest,json=adapterDigest,proto3" json:"adapter_digest,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_api_agentd_v1_agentd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_api_agentd_v1_agentd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_api_agentd_v1_agentd_proto_rawDescGZIP(), []int{4}
}

func (x *Welcome) GetMajor() uint32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *Welcome) GetMinor() uint32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

func (x *Welcome) GetBinding() *Binding {
	if x != nil {
		return x.Binding
	}
	return nil
}

func (x *Welcome) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *Welcome) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *Welcome) GetConnectionEpoch() uint64 {
	if x != nil {
		return x.ConnectionEpoch
	}
	return 0
}

func (x *Welcome) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Welcome) GetLimits() *Limits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *Welcome) GetNegotiationDigest() string {
	if x != nil {
		return x.NegotiationDigest
	}
	return ""
}

func (x *Welcome) GetBuildDigest() string {
	if x != nil {
		return x.BuildDigest
	}
	return ""
}

func (x *Welcome) GetAdapterKind() string {
	if x != nil {
		return x.AdapterKind
	}
	return ""
}

func (x *Welcome) GetAdapterDigest() string {
	if x != nil {
		return x.AdapterDigest
	}
	return ""
}

type Envelope struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Major           uint32                 `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	Minor           uint32                 `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	ConnectionId    string                 `protobuf:"bytes,3,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	ConnectionEpoch uint64                 `protobuf:"varint,4,opt,name=connection_epoch,json=connectionEpoch,proto3" json:"connection_epoch,omitempty"`
	MessageId       string                 `protobuf:"bytes,5,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Sequence        uint64                 `protobuf:"varint,6,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Binding         *Binding               `protobuf:"bytes,7,opt,name=binding,proto3" json:"binding,omitempty"`
	HarnessHandle   string                 `protobuf:"bytes,8,opt,name=harness_handle,json=harnessHandle,proto3" json:"harness_handle,omitempty"`
	OperationId     string                 `protobuf:"bytes,9,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	RequestDigest   string                 `protobuf:"bytes,10,opt,name=request_digest,json=requestDigest,proto3" json:"request_digest,omitempty"`
	SentUnixMs      int64                  `protobuf:"varint,11,opt,name=sent_unix_ms,json=sentUnixMs,proto3" json:"sent_unix_ms,omitempty"`
	DeadlineUnixMs  int64                  `protobuf:"varint,12,opt,name=deadline_unix_ms,json=deadlineUnixMs,proto3" json:"deadline_unix_ms,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*Envelope_Hello
	//	*Envelope_Welcome
	//	*Envelope_Command
	//	*Envelope_Observation
	//	*Envelope_Acknowledgement
	//	*Envelope_Heartbeat
	//	*Envelope_Rotation
	//	*Envelope_Failure
	Body          isEnvelope_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_api_agentd_v1_agentd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_api_agentd_v1_agentd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_api_agentd_v1_agentd_proto_rawDescGZIP(), []int{5}
}

func (x *Envelope) GetMajor() uint32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *Envelope) GetMinor() uint32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

func (x *Envelope) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *Envelope) GetConnectionEpoch() uint64 {
	if x != nil {
		return x.ConnectionEpoch
	}
	return 0
}

func (x *Envelope) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Envelope) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Envelope) GetBinding() *Binding {
	if x != nil {
		return x.Binding
	}
	return nil
}

func (x *Envelope) GetHarnessHandle() string {
	if x != nil {
		return x.HarnessHandle
	}
	return ""
}

func (x *Envelope) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *Envelope) GetRequestDigest() string {
	if x != nil {
		return x.RequestDigest
	}
	return ""
}

func (x *Envelope) GetSentUnixMs() int64 {
	if x != nil {
		return x.SentUnixMs
	}
	return 0
}

func (x *Envelope) GetDeadlineUnixMs() int64 {
	if x != nil {
		return x.DeadlineUnixMs
	}
	return 0
}

func (x *Envelope) GetBody() isEnvelope_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Envelope) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *Envelope) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *Envelope) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *Envelope) GetObservation() *Observation {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Observation); ok {
			return x.Observation
		}
	}
	return nil
}

func (x *Envelope) GetAcknowledgement() *Acknowledgement {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Acknowledgement); ok {
			return x.Acknowledgement
		}
	}
	return nil
}

func (x *Envelope) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *Envelope) GetRotation() *Rotation {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Rotation); ok {
			return x.Rotation
		}
	}
	return nil
}

func (x *Envelope) GetFailure() *Failure {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Failure); ok {
			return x.Failure
		}
	}
	return nil
}

type isEnvelope_Body interface {
	isEnvelope_Body()
}

type Envelope_Hello struct {
	Hello *Hello `protobuf:"bytes,20,opt,name=hello,proto3,oneof"`
}

type Envelope_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,21,opt,name=welcome,proto3,oneof"`
}

type Envelope_Command struct {
	Command *Command `protobuf:"bytes,22,opt,name=command,proto3,oneof"`
}

type Envelope_Observation struct {
	Observation *Observation `protobuf:"bytes,23,opt,name=observation,proto3,oneof"`
}

type Envelope_Acknowledgement struct {
	Acknowledgement *Acknowledgement `protobuf:"bytes,24,opt,name=acknowledgement,proto3,oneof"`
}

type Envelope_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,25,opt,name=heartbeat,proto3,oneof"`
}

type Envelope_Rotation struct {
	Rotation *Rotation `protobuf:"bytes,26,opt,name=rotation,proto3,oneof"`
}

type Envelope_Failure struct {
	Failure *Failure `protobuf:"bytes,27,opt,name=failure,proto3,oneof"`
}

func (*Envelope_Hello) isEnvelope_Body() {}

func (*Envelope_Welcome) isEnvelope_Body() {}

func (*Envelope_Command) isEnvelope_Body() {}

func (*Envelope_Observation) isEnvelope_Body() {}

func (*Envelope_Acknowledgement) isEnvelope_Body() {}

func (*Envelope_Heartbeat) isEnvelope_Body() {}

func (*Envelope_Rotation) isEnvelope_Body() {}

func (*Envelope_Failure) isEnvelope_Body() {}

// Commands reference trusted preconfigured launch/state selections. No arbitrary
// shell, argv, filesystem path, environment map or enterprise credential field.
type Command struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Kind                Command_Kind           `protobuf:"varint,1,opt,name=kind,proto3,enum=thinkpixel.agentd.v1.Command_Kind" json:"kind,omitempty"`
	ConfigurationDigest string                 `protobuf:"bytes,2,opt,name=configuration_digest,json=configurationDigest,proto3" json:"configuration_digest,omitempty"`
	PayloadSchema       string                 `protobuf:"bytes,3,opt,name=payload_schema,json=payloadSchema,proto3" json:"payload_schema,omitempty"`
	Payload             []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                                              // Adapter-negotiated schema; never an unrestricted command.
	ArtifactReference   string                 `protobuf:"bytes,5,opt,name=artifact_reference,json=artifactReference,proto3" json:"artifact_reference,omitempty"` // Mutually exclusive with inline payload.
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_api_agentd_v1_agentd_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_api_agentd_v1_agentd_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_api_agentd_v1_agentd_proto_rawDescGZIP(), []int{6}
}

func (x *Command) GetKind() Command_Kind {
	if x != nil {
		return x.Kind
	}
	return Command_UNSPECIFIED
}

func (x *Command) GetConfigurationDigest() string {
	if x != nil {
		return x.ConfigurationDigest
	}
	return ""
}

func (x *Command) GetPayloadSchema() string {
	if x != nil {
		return x.PayloadSchema
	}
	return ""
}

func (x *Command) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Command) GetArtifactReference() string {
	if x != nil {
		return x.ArtifactReference
	}
	return ""
}

type Observation struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Kind              Observation_Kind       `protobuf:"varint,1,opt,name=kind,proto3,enum=thinkpixel.agentd.v1.Observation_Kind" json:"kind,omitempty"`
	PayloadSchema     string                 `protobuf:"bytes,2,opt,name=payload_schema,json=payloadSchema,proto3" json:"payload_schema,omitempty"`
	Payload           []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	ArtifactReference string                 `protobuf:"bytes,4,opt,name=artifact_reference,json=artifactReference,proto3" json:"artifact_reference,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Observation) Reset() {
	*x = Observation{}
	mi := &file_api_agentd_v1_agentd_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observation) ProtoMessage() {}

func (x *Observation) ProtoReflect() protoreflect.Message {
	mi := &file_api_agentd_v1_agentd_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observation.ProtoReflect.Descriptor instead.
func (*Observation) Descriptor() ([]byte, []int) {
	return file_api_agentd_v1_agentd_proto_rawDescGZIP(), []int{7}
}

func (x *Observation) GetKind() Observation_Kind {
	if x != nil {
		return x.Kind
	}
	return Observation_UNSPECIFIED
}

func (x *Observation) GetPayloadSchema() string {
	if x != nil {
		return x.PayloadSchema
	}
	return ""
}

func (x *Observation) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Observation) GetArtifactReference() string {
	if x != nil {
		return x.ArtifactReference
	}
	return ""
}

type Acknowledgement struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MessageId        string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	RequestDigest    string                 `protobuf:"bytes,2,opt,name=request_digest,json=requestDigest,proto3" json:"request_digest,omitempty"`
	AcceptedSequence uint64                 `protobuf:"varint,3,opt,name=accepted_sequence,json=acceptedSequence,proto3" json:"accepted_sequence,omitempty"`
	EventCredit      uint32                 `protobuf:"varint,4,opt,name=event_credit,json=eventCredit,proto3" json:"event_credit,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Acknowledgement) Reset() {
	*x = Acknowledgement{}
	mi := &file_api_agentd_v1_agentd_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Acknowledgement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Acknowledgement) ProtoMessage() {}

func (x *Acknowledgement) ProtoReflect() protoreflect.Message {
	mi := &file_api_agentd_v1_agentd_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Acknowledgement.ProtoReflect.Descriptor instead.
func (*Acknowledgement) Descriptor() ([]byte, []int) {
	return file_api_agentd_v1_agentd_proto_rawDescGZIP(), []int{8}
}

func (x *Acknowledgement) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Acknowledgement) GetRequestDigest() string {
	if x != nil {
		return x.RequestDigest
	}
	return ""
}

func (x *Acknowledgement) GetAcceptedSequence() uint64 {
	if x != nil {
		return x.AcceptedSequence
	}
	return 0
}

func (x *Acknowledgement) GetEventCredit() uint32 {
	if x != nil {
		return x.EventCredit
	}
	return 0
}

type Heartbeat struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ProcessState         Heartbeat_ProcessState `protobuf:"varint,1,opt,name=process_state,json=processState,proto3,enum=thinkpixel.agentd.v1.Heartbeat_ProcessState" json:"process_state,omitempty"`
	LastAcceptedSequence uint64                 `protobuf:"varint,2,opt,name=last_accepted_sequence,json=lastAcceptedSequence,proto3" json:"last_accepted_sequence,omitempty"`
	LastProducedSequence uint64                 `protobuf:"varint,3,opt,name=last_produced_sequence,json=lastProducedSequence,proto3" json:"last_produced_sequence,omitempty"`
	ActiveOperationId    string                 `protobuf:"bytes,4,opt,name=active_operation_id,json=activeOperationId,proto3" json:"active_operation_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_api_agentd_v1_agentd_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_api_agentd_v1_agentd_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_api_agentd_v1_agentd_proto_rawDescGZIP(), []int{9}
}

func (x *Heartbeat) GetProcessState() Heartbeat_ProcessState {
	if x != nil {
		return x.ProcessState
	}
	return Heartbeat_UNSPECIFIED
}

func (x *Heartbeat) GetLastAcceptedSequence() uint64 {
	if x != nil {
		return x.LastAcceptedSequence
	}
	return 0
}

func (x *Heartbeat) GetLastProducedSequence() uint64 {
	if x != nil {
		return x.LastProducedSequence
	}
	return 0
}

func (x *Heartbeat) GetActiveOperationId() string {
	if x != nil {
		return x.ActiveOperationId
	}
	return ""
}

type Rotation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           Rotation_Kind          `protobuf:"varint,1,opt,name=kind,proto3,enum=thinkpixel.agentd.v1.Rotation_Kind" json:"kind,omitempty"`
	CertificatePem []byte                 `protobuf:"bytes,2,opt,name=certificate_pem,json=certificatePem,proto3" json:"certificate_pem,omitempty"`
	PrivateKeyPem  []byte                 `protobuf:"bytes,3,opt,name=private_key_pem,json=privateKeyPem,proto3" json:"private_key_pem,omitempty"` // Ephemeral transport secret; never logged/persisted.
	ExpiresUnixMs  int64                  `protobuf:"varint,4,opt,name=expires_unix_ms,json=expiresUnixMs,proto3" json:"expires_unix_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Rotation) Reset() {
	*x = Rotation{}
	mi := &file_api_agentd_v1_agentd_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rotation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rotation) ProtoMessage() {}

func (x *Rotation) ProtoReflect() protoreflect.Message {
	mi := &file_api_agentd_v1_agentd_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rotation.ProtoReflect.Descriptor instead.
func (*Rotation) Descriptor() ([]byte, []int) {
	return file_api_agentd_v1_agentd_proto_rawDescGZIP(), []int{10}
}

func (x *Rotation) GetKind() Rotation_Kind {
	if x != nil {
		return x.Kind
	}
	return Rotation_UNSPECIFIED
}

func (x *Rotation) GetCertificatePem() []byte {
	if x != nil {
		return x.CertificatePem
	}
	return nil
}

func (x *Rotation) GetPrivateKeyPem() []byte {
	if x != nil {
		return x.PrivateKeyPem
	}
	return nil
}

func (x *Rotation) GetExpiresUnixMs() int64 {
	if x != nil {
		return x.ExpiresUnixMs
	}
	return 0
}

type Failure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          Failure_Code           `protobuf:"varint,1,opt,name=code,proto3,enum=thinkpixel.agentd.v1.Failure_Code" json:"code,omitempty"` // Closed safe codes; no attacker-controlled error text.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Failure) Reset() {
	*x = Failure{}
	mi := &file_api_agentd_v1_agentd_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Failure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Failure) ProtoMessage() {}

func (x *Failure) ProtoReflect() protoreflect.Message {
	mi := &file_api_agentd_v1_agentd_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Failure.ProtoReflect.Descriptor instead.
func (*Failure) Descriptor() ([]byte, []int) {
	return file_api_agentd_v1_agentd_proto_rawDescGZIP(), []int{11}
}

func (x *Failure) GetCode() Failure_Code {
	if x != nil {
		return x.Code
	}
	return Failure_UNSPECIFIED
}

var File_api_agentd_v1_agentd_proto protoreflect.FileDescriptor

const file_api_agentd_v1_agentd_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/agentd/v1/agentd.proto\x12\x14thinkpixel.agentd.v1\"n\n" +
	"\fVersionRange\x12\x14\n" +
	"\x05major\x18\x01 \x01(\rR\x05major\x12#\n" +
	"\rminimum_minor\x18\x02 \x01(\rR\fminimumMinor\x12#\n" +
	"\rmaximum_minor\x18\x03 \x01(\rR\fmaximumMinor\"\xe4\x01\n" +
	"\aBinding\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12!\n" +
	"\fexecution_id\x18\x03 \x01(\tR\vexecutionId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x04 \x01(\tR\tattemptId\x12,\n" +
	"\x12sandbox_binding_id\x18\x05 \x01(\tR\x10sandboxBindingId\x12-\n" +
	"\x12session_generation\x18\x06 \x01(\x04R\x11sessionGeneration\"\xa6\x03\n" +
	"\x06Limits\x12\x1f\n" +
	"\vframe_bytes\x18\x01 \x01(\rR\n" +
	"frameBytes\x12#\n" +
	"\rcommand_bytes\x18\x02 \x01(\rR\fcommandBytes\x12\x1f\n" +
	"\vevent_bytes\x18\x03 \x01(\rR\n" +
	"eventBytes\x12)\n" +
	"\x10diagnostic_bytes\x18\x04 \x01(\rR\x0fdiagnosticBytes\x12+\n" +
	"\x11mutating_inflight\x18\x05 \x01(\rR\x10mutatingInflight\x12+\n" +
	"\x11readonly_inflight\x18\x06 \x01(\rR\x10readonlyInflight\x12'\n" +
	"\x0fbuffered_events\x18\a \x01(\rR\x0ebufferedEvents\x12%\n" +
	"\x0ebuffered_bytes\x18\b \x01(\rR\rbufferedBytes\x122\n" +
	"\x15heartbeat_interval_ms\x18\t \x01(\rR\x13heartbeatIntervalMs\x12,\n" +
	"\x12liveness_window_ms\x18\n" +
	" \x01(\rR\x10livenessWindowMs\"\xd6\x03\n" +
	"\x05Hello\x12>\n" +
	"\bversions\x18\x01 \x01(\v2\".thinkpixel.agentd.v1.VersionRangeR\bversions\x127\n" +
	"\abinding\x18\x02 \x01(\v2\x1d.thinkpixel.agentd.v1.BindingR\abinding\x12\x1c\n" +
	"\tchallenge\x18\x03 \x01(\fR\tchallenge\x12!\n" +
	"\fbuild_digest\x18\x04 \x01(\tR\vbuildDigest\x12!\n" +
	"\fadapter_kind\x18\x05 \x01(\tR\vadapterKind\x12%\n" +
	"\x0eadapter_digest\x18\x06 \x01(\tR\radapterDigest\x125\n" +
	"\x16supported_capabilities\x18\a \x03(\tR\x15supportedCapabilities\x123\n" +
	"\x15required_capabilities\x18\b \x03(\tR\x14requiredCapabilities\x124\n" +
	"\x06limits\x18\t \x01(\v2\x1c.thinkpixel.agentd.v1.LimitsR\x06limits\x12'\n" +
	"\x0fbootstrap_proof\x18\n" +
	" \x01(\fR\x0ebootstrapProof\"\xd2\x03\n" +
	"\aWelcome\x12\x14\n" +
	"\x05major\x18\x01 \x01(\rR\x05major\x12\x14\n" +
	"\x05minor\x18\x02 \x01(\rR\x05minor\x127\n" +
	"\abinding\x18\x03 \x01(\v2\x1d.thinkpixel.agentd.v1.BindingR\abinding\x12\x1c\n" +
	"\tchallenge\x18\x04 \x01(\fR\tchallenge\x12#\n" +
	"\rconnection_id\x18\x05 \x01(\tR\fconnectionId\x12)\n" +
	"\x10connection_epoch\x18\x06 \x01(\x04R\x0fconnectionEpoch\x12\"\n" +
	"\fcapabilities\x18\a \x03(\tR\fcapabilities\x124\n" +
	"\x06limits\x18\b \x01(\v2\x1c.thinkpixel.agentd.v1.LimitsR\x06limits\x12-\n" +
	"\x12negotiation_digest\x18\t \x01(\tR\x11negotiationDigest\x12!\n" +
	"\fbuild_digest\x18\n" +
	" \x01(\tR\vbuildDigest\x12!\n" +
	"\fadapter_kind\x18\v \x01(\tR\vadapterKind\x12%\n" +
	"\x0eadapter_digest\x18\f \x01(\tR\radapterDigest\"\xbe\a\n" +
	"\bEnvelope\x12\x14\n" +
	"\x05major\x18\x01 \x01(\rR\x05major\x12\x14\n" +
	"\x05minor\x18\x02 \x01(\rR\x05minor\x12#\n" +
	"\rconnection_id\x18\x03 \x01(\tR\fconnectionId\x12)\n" +
	"\x10connection_epoch\x18\x04 \x01(\x04R\x0fconnectionEpoch\x12\x1d\n" +
	"\n" +
	"message_id\x18\x05 \x01(\tR\tmessageId\x12\x1a\n" +
	"\bsequence\x18\x06 \x01(\x04R\bsequence\x127\n" +
	"\abinding\x18\a \x01(\v2\x1d.thinkpixel.agentd.v1.BindingR\abinding\x12%\n" +
	"\x0eharness_handle\x18\b \x01(\tR\rharnessHandle\x12!\n" +
	"\foperation_id\x18\t \x01(\tR\voperationId\x12%\n" +
	"\x0erequest_digest\x18\n" +
	" \x01(\tR\rrequestDigest\x12 \n" +
	"\fsent_unix_ms\x18\v \x01(\x03R\n" +
	"sentUnixMs\x12(\n" +
	"\x10deadline_unix_ms\x18\f \x01(\x03R\x0edeadlineUnixMs\x123\n" +
	"\x05hello\x18\x14 \x01(\v2\x1b.thinkpixel.agentd.v1.HelloH\x00R\x05hello\x129\n" +
	"\awelcome\x18\x15 \x01(\v2\x1d.thinkpixel.agentd.v1.WelcomeH\x00R\awelcome\x129\n" +
	"\acommand\x18\x16 \x01(\v2\x1d.thinkpixel.agentd.v1.CommandH\x00R\acommand\x12E\n" +
	"\vobservation\x18\x17 \x01(\v2!.thinkpixel.agentd.v1.ObservationH\x00R\vobservation\x12Q\n" +
	"\x0facknowledgement\x18\x18 \x01(\v2%.thinkpixel.agentd.v1.AcknowledgementH\x00R\x0facknowledgement\x12?\n" +
	"\theartbeat\x18\x19 \x01(\v2\x1f.thinkpixel.agentd.v1.HeartbeatH\x00R\theartbeat\x12<\n" +
	"\brotation\x18\x1a \x01(\v2\x1e.thinkpixel.agentd.v1.RotationH\x00R\brotation\x129\n" +
	"\afailure\x18\x1b \x01(\v2\x1d.thinkpixel.agentd.v1.FailureH\x00R\afailureB\x06\n" +
	"\x04body\"\xec\x02\n" +
	"\aCommand\x126\n" +
	"\x04kind\x18\x01 \x01(\x0e2\".thinkpixel.agentd.v1.Command.KindR\x04kind\x121\n" +
	"\x14configuration_digest\x18\x02 \x01(\tR\x13configurationDigest\x12%\n" +
	"\x0epayload_schema\x18\x03 \x01(\tR\rpayloadSchema\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12-\n" +
	"\x12artifact_reference\x18\x05 \x01(\tR\x11artifactReference\"\x85\x01\n" +
	"\x04Kind\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\t\n" +
	"\x05START\x10\x01\x12\b\n" +
	"\x04STOP\x10\x02\x12\v\n" +
	"\aRESTART\x10\x03\x12\r\n" +
	"\tINTERRUPT\x10\x04\x12\n" +
	"\n" +
	"\x06STATUS\x10\x05\x12\x16\n" +
	"\x12PREPARE_CHECKPOINT\x10\x06\x12\v\n" +
	"\aEXECUTE\x10\a\x12\n" +
	"\n" +
	"\x06SIGNAL\x10\b\"\xa4\x02\n" +
	"\vObservation\x12:\n" +
	"\x04kind\x18\x01 \x01(\x0e2&.thinkpixel.agentd.v1.Observation.KindR\x04kind\x12%\n" +
	"\x0epayload_schema\x18\x02 \x01(\tR\rpayloadSchema\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12-\n" +
	"\x12artifact_reference\x18\x04 \x01(\tR\x11artifactReference\"i\n" +
	"\x04Kind\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0ePROCESS_STATUS\x10\x01\x12\x13\n" +
	"\x0fCANDIDATE_EVENT\x10\x02\x12\x17\n" +
	"\x13CHECKPOINT_PREPARED\x10\x03\x12\x0e\n" +
	"\n" +
	"DIAGNOSTIC\x10\x04\"\xa7\x01\n" +
	"\x0fAcknowledgement\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12%\n" +
	"\x0erequest_digest\x18\x02 \x01(\tR\rrequestDigest\x12+\n" +
	"\x11accepted_sequence\x18\x03 \x01(\x04R\x10acceptedSequence\x12!\n" +
	"\fevent_credit\x18\x04 \x01(\rR\veventCredit\"\xe8\x02\n" +
	"\tHeartbeat\x12Q\n" +
	"\rprocess_state\x18\x01 \x01(\x0e2,.thinkpixel.agentd.v1.Heartbeat.ProcessStateR\fprocessState\x124\n" +
	"\x16last_accepted_sequence\x18\x02 \x01(\x04R\x14lastAcceptedSequence\x124\n" +
	"\x16last_produced_sequence\x18\x03 \x01(\x04R\x14lastProducedSequence\x12.\n" +
	"\x13active_operation_id\x18\x04 \x01(\tR\x11activeOperationId\"l\n" +
	"\fProcessState\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06ABSENT\x10\x01\x12\f\n" +
	"\bSTARTING\x10\x02\x12\v\n" +
	"\aRUNNING\x10\x03\x12\f\n" +
	"\bSTOPPING\x10\x04\x12\n" +
	"\n" +
	"\x06EXITED\x10\x05\x12\n" +
	"\n" +
	"\x06FAILED\x10\x06\"\xee\x01\n" +
	"\bRotation\x127\n" +
	"\x04kind\x18\x01 \x01(\x0e2#.thinkpixel.agentd.v1.Rotation.KindR\x04kind\x12'\n" +
	"\x0fcertificate_pem\x18\x02 \x01(\fR\x0ecertificatePem\x12&\n" +
	"\x0fprivate_key_pem\x18\x03 \x01(\fR\rprivateKeyPem\x12&\n" +
	"\x0fexpires_unix_ms\x18\x04 \x01(\x03R\rexpiresUnixMs\"0\n" +
	"\x04Kind\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\v\n" +
	"\aREQUEST\x10\x01\x12\n" +
	"\n" +
	"\x06ISSUED\x10\x02\"\xc0\x01\n" +
	"\aFailure\x126\n" +
	"\x04code\x18\x01 \x01(\x0e2\".thinkpixel.agentd.v1.Failure.CodeR\x04code\"}\n" +
	"\x04Code\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x10\n" +
	"\fINCOMPATIBLE\x10\x01\x12\t\n" +
	"\x05STALE\x10\x02\x12\r\n" +
	"\tMALFORMED\x10\x03\x12\x12\n" +
	"\x0eLIMIT_EXCEEDED\x10\x04\x12\x0f\n" +
	"\vUNAVAILABLE\x10\x05\x12\x13\n" +
	"\x0fOUTCOME_UNKNOWN\x10\x062_\n" +
	"\x0eAgentTransport\x12M\n" +
	"\aConnect\x12\x1e.thinkpixel.agentd.v1.Envelope\x1a\x1e.thinkpixel.agentd.v1.Envelope(\x010\x01B9Z7github.com/bdobrica/ThinkPixelAR/api/agentd/v1;agentdv1b\x06proto3"

var (
	file_api_agentd_v1_agentd_proto_rawDescOnce sync.Once
	file_api_agentd_v1_agentd_proto_rawDescData []byte
)

func file_api_agentd_v1_agentd_proto_rawDescGZIP() []byte {
	file_api_agentd_v1_agentd_proto_rawDescOnce.Do(func() {
		file_api_agentd_v1_agentd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_agentd_v1_agentd_proto_rawDesc), len(file_api_agentd_v1_agentd_proto_rawDesc)))
	})
	return file_api_agentd_v1_agentd_proto_rawDescData
}

var file_api_agentd_v1_agentd_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_api_agentd_v1_agentd_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_agentd_v1_agentd_proto_goTypes = []any{
	(Command_Kind)(0),           // 0: thinkpixel.agentd.v1.Command.Kind
	(Observation_Kind)(0),       // 1: thinkpixel.agentd.v1.Observation.Kind
	(Heartbeat_ProcessState)(0), // 2: thinkpixel.agentd.v1.Heartbeat.ProcessState
	(Rotation_Kind)(0),          // 3: thinkpixel.agentd.v1.Rotation.Kind
	(Failure_Code)(0),           // 4: thinkpixel.agentd.v1.Failure.Code
	(*VersionRange)(nil),        // 5: thinkpixel.agentd.v1.VersionRange
	(*Binding)(nil),             // 6: thinkpixel.agentd.v1.Binding
	(*Limits)(nil),              // 7: thinkpixel.agentd.v1.Limits
	(*Hello)(nil),               // 8: thinkpixel.agentd.v1.Hello
	(*Welcome)(nil),             // 9: thinkpixel.agentd.v1.Welcome
	(*Envelope)(nil),            // 10: thinkpixel.agentd.v1.Envelope
	(*Command)(nil),             // 11: thinkpixel.agentd.v1.Command
	(*Observation)(nil),         // 12: thinkpixel.agentd.v1.Observation
	(*Acknowledgement)(nil),     // 13: thinkpixel.agentd.v1.Acknowledgement
	(*Heartbeat)(nil),           // 14: thinkpixel.agentd.v1.Heartbeat
	(*Rotation)(nil),            // 15: thinkpixel.agentd.v1.Rotation
	(*Failure)(nil),             // 16: thinkpixel.agentd.v1.Failure
}
var file_api_agentd_v1_agentd_proto_depIdxs = []int32{
	5,  // 0: thinkpixel.agentd.v1.Hello.versions:type_name -> thinkpixel.agentd.v1.VersionRange
	6,  // 1: thinkpixel.agentd.v1.Hello.binding:type_name -> thinkpixel.agentd.v1.Binding
	7,  // 2: thinkpixel.agentd.v1.Hello.limits:type_name -> thinkpixel.agentd.v1.Limits
	6,  // 3: thinkpixel.agentd.v1.Welcome.binding:type_name -> thinkpixel.agentd.v1.Binding
	7,  // 4: thinkpixel.agentd.v1.Welcome.limits:type_name -> thinkpixel.agentd.v1.Limits
	6,  // 5: thinkpixel.agentd.v1.Envelope.binding:type_name -> thinkpixel.agentd.v1.Binding
	8,  // 6: thinkpixel.agentd.v1.Envelope.hello:type_name -> thinkpixel.agentd.v1.Hello
	9,  // 7: thinkpixel.agentd.v1.Envelope.welcome:type_name -> thinkpixel.agentd.v1.Welcome
	11, // 8: thinkpixel.agentd.v1.Envelope.command:type_name -> thinkpixel.agentd.v1.Command
	12, // 9: thinkpixel.agentd.v1.Envelope.observation:type_name -> thinkpixel.agentd.v1.Observation
	13, // 10: thinkpixel.agentd.v1.Envelope.acknowledgement:type_name -> thinkpixel.agentd.v1.Acknowledgement
	14, // 11: thinkpixel.agentd.v1.Envelope.heartbeat:type_name -> thinkpixel.agentd.v1.Heartbeat
	15, // 12: thinkpixel.agentd.v1.Envelope.rotation:type_name -> thinkpixel.agentd.v1.Rotation
	16, // 13: thinkpixel.agentd.v1.Envelope.failure:type_name -> thinkpixel.agentd.v1.Failure
	0,  // 14: thinkpixel.agentd.v1.Command.kind:type_name -> thinkpixel.agentd.v1.Command.Kind
	1,  // 15: thinkpixel.agentd.v1.Observation.kind:type_name -> thinkpixel.agentd.v1.Observation.Kind
	2,  // 16: thinkpixel.agentd.v1.Heartbeat.process_state:type_name -> thinkpixel.agentd.v1.Heartbeat.ProcessState
	3,  // 17: thinkpixel.agentd.v1.Rotation.kind:type_name -> thinkpixel.agentd.v1.Rotation.Kind
	4,  // 18: thinkpixel.agentd.v1.Failure.code:type_name -> thinkpixel.agentd.v1.Failure.Code
	10, // 19: thinkpixel.agentd.v1.AgentTransport.Connect:input_type -> thinkpixel.agentd.v1.Envelope
	10, // 20: thinkpixel.agentd.v1.AgentTransport.Connect:output_type -> thinkpixel.agentd.v1.Envelope
	20, // [20:21] is the sub-list for method output_type
	19, // [19:20] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_api_agentd_v1_agentd_proto_init() }
func file_api_agentd_v1_agentd_proto_init() {
	if File_api_agentd_v1_agentd_proto != nil {
		return
	}
	file_api_agentd_v1_agentd_proto_msgTypes[5].OneofWrappers = []any{
		(*Envelope_Hello)(nil),
		(*Envelope_Welcome)(nil),
		(*Envelope_Command)(nil),
		(*Envelope_Observation)(nil),
		(*Envelope_Acknowledgement)(nil),
		(*Envelope_Heartbeat)(nil),
		(*Envelope_Rotation)(nil),
		(*Envelope_Failure)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_agentd_v1_agentd_proto_rawDesc), len(file_api_agentd_v1_agentd_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_agentd_v1_agentd_proto_goTypes,
		DependencyIndexes: file_api_agentd_v1_agentd_proto_depIdxs,
		EnumInfos:         file_api_agentd_v1_agentd_proto_enumTypes,
		MessageInfos:      file_api_agentd_v1_agentd_proto_msgTypes,
	}.Build()
	File_api_agentd_v1_agentd_proto = out.File
	file_api_agentd_v1_agentd_proto_goTypes = nil
	file_api_agentd_v1_agentd_proto_depIdxs = nil
}
