apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ar-bounded-scratch-v1
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
allowVolumeExpansion: false
